// File generated by Antigravity AI Assistant for project `kin-banking`.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqzbygXnRa0xBlaaz24mg0LBj22AC0KDA',
    appId: '1:381692013422:web:4a43802bba2af8d0e7ef7f',
    messagingSenderId: '381692013422',
    projectId: 'kin-banking',
    authDomain: 'kin-banking.firebaseapp.com',
    storageBucket: 'kin-banking.firebasestorage.app',
    measurementId: 'G-C7Y7W8QTV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyYdgrZAPKdDAymPb-57FcEEa5UTitmOg',
    appId: '1:381692013422:android:02820fc3786cd087e7ef7f',
    messagingSenderId: '381692013422',
    projectId: 'kin-banking',
    storageBucket: 'kin-banking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7KxpwKlkFy8ceuPafTI1ijbFGDBqJhTM',
    appId: '1:381692013422:ios:8eea82e21c686867e7ef7f',
    messagingSenderId: '381692013422',
    projectId: 'kin-banking',
    storageBucket: 'kin-banking.firebasestorage.app',
    iosBundleId: 'com.studio.kinapp.bnk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7KxpwKlkFy8ceuPafTI1ijbFGDBqJhTM',
    appId: '1:381692013422:ios:8eea82e21c686867e7ef7f',
    messagingSenderId: '381692013422',
    projectId: 'kin-banking',
    storageBucket: 'kin-banking.firebasestorage.app',
    iosBundleId: 'com.studio.kinapp.bnk',
  );
}
